<?php
    return [
        'IMAGE_TYPE' => [
            // unit of size is kilobytes
            'LIMIT_SIZE' => '20480'
        ],
        'status_code_after_redeem' => [
            'success' => 0,
            'activated' => 1,
            'pending' => 2,
            'out_of_quota' => 3,
            'topup_fail' => 4
        ],
        'sort_by' => [
            'asc' => 1,
            'desc' => 2
        ],
        'roles' => [
            'admin' => [
                'key' => 1,
                'name' => 'admin',
                'permissions' => [
                    'user_manager',
                    'config_manager',
                    'report',
                    'approve_user',
                    'campaign_manager',
                    'code_manager',
                    'issue_manager',
                ]
            ],
            'manager' => [
                'key' => 2,
                'name' => 'manager',
                'permissions' => [
                    'report',
                    'approve_user',
                    'campaign_manager',
                    'code_manager',
                    'issue_manager',
                ]
            ],
            'member' => [
                'key' => 3,
                'name' => 'member',
                'permissions' => [
                    'report',
                    'approve_user',
                ]
            ],
            'system' => [
                'key' => 4,
                'name' => 'system',
                'permissions' => []
            ],
        ],
        'pagination' => [
            'per_page' => 20,
            'max_per_page' => 500,
            'current_page' => 1,
        ],
        'status' => [
            'user'  => [
                'active'   => 0,
                'deactive' => 1,
            ],
        ],
        'type' => [
            'code' => [
                'card' => 1,
                'market' => 2
            ]
        ],
        'min' => [
            'type' => 1,
            'amount' => 0
        ],
        'failed_ip' => [
            // limit how many failed times of ip
            'limit' => 5,
            // unblock after ... minutes
            'unblock_after' => 180
        ],
        'timelife_otp' => [
            //timelife...minutes
            'one' => 1,
            'two' => 2
        ],
        'error_code' => [
            'phone_not_found_phonecheck' => 101,
            'customer_pending_phonecheck' => 102,
            'invalid_data_phonecheck' => 105,
            'ip_blocked_phonecheck' => 199,
            'image_size_large' => 192,
            'phone_blocking_phonecheck' => 188,
            'failed_OTP_phonevalidate'  => 103,
            'failed_top_up_phonevalidate' => 104,
            'invalid_data_phonevalidate' => 283,
            'campaign_not_found_phoneotp' => 107,
            'invalid_data_phoneotp' => 106,
            'code_invalid_phoneotp' => 108,
            'customer_not_found_phoneotp' => 110,
            'account_locked_phoneotp' => 150,
            'send_otp_failed_phoneotp' => 111,
            'create_transaction_failed_phoneotp' => 112,
            'account_locked_phonevalidate' => 114,
            'transaction_invalid_phonevalidate' => 115,
            'phone_not_found_phonevalidate' => 101,
            'OTP_expired_phonevalidate' => 117,
            'transaction_item_not_found_phonevalidate' => 118,
            'code_not_found_phonevalidate' => 119,
            'code_invalid_phonevalidate' => 121,
            'province_not_found_phonecreate' => 124,
            'invalid_data_phonecreate' => 123,
            'campaign_not_found_phonecreate' => 125,
            'code_invalid_phonecreate' => 126,
            'campaign_invalid_phonecreate' => 127,
            'save_customer_failed_phonecreate' => 128,
            'invalid_data_giftcodecheck' => 169,
            'campaign_not_found_giftcodecheck' => 130,
            'campaign_invalid_giftcodecheck' => 131,
            'code_not_found_giftcodecheck' => 132,
            'code_invalid_giftcodecheck' => 133,
            'wrong_OTP_giftcodecheck' => 134,
            'customer_not_found_redeemretry' => 136,
            'failed_top_up_redeemretry' => 166,
            'transaction_not_found_redeemretry' => 137,
            'invalid_data_redeemretry' => 135,
            'transaction_invalid_redeemretry' => 138,
            'campaign_not_found_redeemretry' => 139,
            'transaction_item_not_found_redeemretry' => 140,
            'code_not_found_redeemretry' => 141,
            'code_invalid_redeemretry' => 142,
            'save_campaign_failed_postcampaigns' => 202,
            'invalid_data_postcampaigns' => 201,
            'invalid_data_deletecampaigns' => 282,
            'invalid_data_campaigngenerate' => 278,
            'campaign_not_found_putcampaigns' => 204,
            'update_campaign_failed_putcampaigns' => 205,
            'invalid_campaign_putcampaigns' => 203,
            'campaign_not_found_patchcampaigns' => 207,
            'update_status_campaign_failed_patchcampaigns' => 208,
            'invalid_data_patchcampaigns' => 206,
            'code_not_found_patchcodes' => 212,
            'update_status_code_failed_patchcodes' => 213,
            'invalid_data_patchcodes' => 211,
            'code_not_found_putcodes' => 215,
            'invalid_data_list' => 287,
            'update_status_code_failed_putcodes' => 216,
            'invalid_data_putcodes' => 214,
            'delete_code_failed_deletecode' => 247,
            'invalid_data_deletecode' => 267,
            'customer_not_found_getcustomers' => 218,
            'customer_not_found_putcustomers' => 220,
            'invalid_data_putcustomer' => 266,
            'update_customer_failed_putcustomers' => 221,
            'invalid_data_putcustomers' => 219,
            'customer_not_found_patchcustomers' => 223,
            'update_status_customer_failed_patchcustomers' => 224,
            'invalid_data_importcustomers' => 272,
            'invalid_data_patchcustomers' => 222,
            'customer_not_found_deletecustomers' => 225,
            'delete_customer_failed_deletecustomers' => 226,
            'customer_not_found_deletecustomerslist' => 228,
            'delete_customer_failed_deletecustomerslist' => 229,
            'invalid_data_deletecustomerslist' => 227,
            'user_not_found_putuserprofile' => 232,
            'invalid_data_putuserprofile' => 231,
            'update_user_failed_putuserprofile' => 233,
            'user_not_found_getuserprofile' => 234,
            'current_password_failed_putuser' => 236,
            'invalid_data_putuserchangepass' => 288,
            'invalid_data_putuser' => 235,
            'phone_min_putuser' => 251,
            'save_user_failed_postuser' => 238,
            'create_dont_permission_postuser' => 239,
            'phone_min_postuser' => 250,
            'invalid_data_postuser' => 237,
            'invalid_data_postuserlogin' => 286,
            'invalid_data_deleteusers' => 269,
            'permisson_failed' => 240,
            'campaign_not_found_getcampaigns' => 280,
            'transactions_not_found_transactions' => 299,
            'invalid_data_postzone' => 290,
            'save_zone_failed_postzones' => 291,
            'zone_not_found_patchzones'  => 292,
            'invalid_data_deletezones' => 268,
            'save_zone_province_failed_postzoneprovince' =>293,
            'zone_province_not_found_patchzoneprovinces' =>294,
            'zone_province_delete_fail_zoneprovinces' => 295,
            'create_transaction_failed_createtranbycode' =>296,
            'invalid_data_postcreatetranbycodes' => 297,
            'code_invalid_createtransacbycode' => 298,
            'zone_not_found_getzones' => 299,
            'invalid_data_postredeem' => 300,
            'customer_not_found_postredeem' => 301,
            'transaction_not_found_postredeem' => 302,
            'failed_top_up_postredeem' => 303,
            'transaction_item_not_found_postredeem' => 304,
            '3rd_code_invalid_phoneotp' => 305,
            '3rd_send_otp_failed' => 306,
            'province_not_found_getprovincesbyzoneid' => 255,
            'campaign_not_found_middlewarecampaign' => 191,
            'campaign_invalid_middlewarecampaign' => 190,
            'campaign_not_found_campaignconfig' => 245,
            'invalid_data_campaignconfig' => 270,
            'create_campaign_config_failed_campaignconfig' => 246,
            'invalid_data_postcampaignconfig' => 271,
            'update_config_failed_putconfig' => 248,
            'invalid_data_putconfig' => 273,
            'update_zone_province_failed_patchzoneprovinces' => 249,
            'campaign_not_found_postnapthe' => 307
        ],
    ]
?>
